server.port=8081
spring.application.name=kafka-producer-service

# Both brokers listed for redundancy, if one is down, producer connects to the other
spring.kafka.bootstrap-servers=localhost:9092,localhost:9192

# Metadata refresh interval: how often producer re-fetches cluster info (default 5 min)
spring.kafka.producer.properties.metadata.max.age.ms=300000

# Asking broker to reply only when all ISR successfully get the events
spring.kafka.producer.acks=all

#-------------SERIALIZER-------------
# Key needs to be String
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# Value: JsonSerializer, auto-converts Java objects to JSON bytes
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


#-------------RECORD ACCUMULATOR-------------
# Batching, wait 20ms to collect more messages before sending
spring.kafka.producer.properties.linger.ms=20

# Max batch size, send when batch reaches 32KB (even if linger.ms hasn't expired)
spring.kafka.producer.properties.batch.size=32768